data:
    type: "Setdataset"
    train_dataset: "MSRS"
    val_dataset: "MSRS"
    patch_size: 64
    channels: 3
    num_workers: 0
    data_dir: "./data/MSRS"
    ckpt_dir: "pretrain_models/"
    conditional: True

model:
    in_channels: 5
    out_ch: 1
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200

training:
    batch_size: 1
    n_epochs: 1
    validation_freq: 100000

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8
